import datetime
from django.core.management.base import BaseCommand, CommandError
from django.contrib.auth.models import User
from django.conf import settings
from django.db import transaction
from pbf.models import *

spirits = (
        ["Bringer"],
        ["Downpour"],
        ["Earth"],
        ["Fangs"],
        ["Finder"],
        ["Fractured"],
        ["Green"],
        ["Keeper"],
        ["Lightning"],
        ["Lure"],
        ["Minds"],
        ["Mist"],
        ["Ocean"],
        ["River"],
        ["Serpent"],
        ["Shadows"],
        ["Shifting"],
        ["Starlight"],
        ["Stone"],
        ["Thunderspeaker"],
        ["Trickster"],
        ["Vengeance"],
        ["Volcano"],
        ["Wildfire"],
)

cards = (
        ["Shatter Homesteads", Card.UNIQUE, "Lightning"],
        ["Raging Storm", Card.UNIQUE, "Lightning"],
        ["Lightning's Boon", Card.UNIQUE, "Lightning"],
        ["Harbingers of the Lightning", Card.UNIQUE, "Lightning"],
        ["Flash Floods", Card.UNIQUE, "River"],
        ["Wash Away", Card.UNIQUE, "River"],
        ["Boon of Vigor", Card.UNIQUE, "River"],
        ["River's Bounty", Card.UNIQUE, "River"],
        ["Concealing Shadows", Card.UNIQUE, "Shadows"],
        ["Favors Called Due", Card.UNIQUE, "Shadows"],
        ["Mantle of Dread", Card.UNIQUE, "Shadows"],
        ["Crops Wither and Fade", Card.UNIQUE, "Shadows"],
        ["Guard the Healing Land", Card.UNIQUE, "Earth"],
        ["A Year of Perfect Stillness", Card.UNIQUE, "Earth"],
        ["Rituals of Destruction", Card.UNIQUE, "Earth"],
        ["Draw of the Fruitful Earth", Card.UNIQUE, "Earth"],
        ["Manifestation of Power and Glory", Card.UNIQUE, "Thunderspeaker"],
        ["Words of Warning", Card.UNIQUE, "Thunderspeaker"],
        ["Sudden Ambush", Card.UNIQUE, "Thunderspeaker"],
        ["Voice of Thunder", Card.UNIQUE, "Thunderspeaker"],
        ["Call of the Deeps", Card.UNIQUE, "Ocean"],
        ["Grasping Tide", Card.UNIQUE, "Ocean"],
        ["Swallow the Land-Dwellers", Card.UNIQUE, "Ocean"],
        ["Tidal Boon", Card.UNIQUE, "Ocean"],
        ["Predatory Nightmares", Card.UNIQUE, "Bringer"],
        ["Dread Apparitions", Card.UNIQUE, "Bringer"],
        ["Call on Midnight's Dream", Card.UNIQUE, "Bringer"],
        ["Dreams of the Dahan", Card.UNIQUE, "Bringer"],
        ["Overgrow in a Night", Card.UNIQUE, "Green"],
        ["Gift of Proliferation", Card.UNIQUE, "Green"],
        ["Fields Choked with Growth", Card.UNIQUE, "Green"],
        ["Stem the Flow of Fresh Water", Card.UNIQUE, "Green"],
        ["Savage Mawbeasts", Card.MINOR],
        ["Voracious Growth", Card.MINOR],
        ["Rouse the Trees and Stones", Card.MINOR],
        ["Encompassing Ward", Card.MINOR],
        ["Song of Sanctity", Card.MINOR],
        ["Uncanny Melting", Card.MINOR],
        ["Shadows of the Burning Forest", Card.MINOR],
        ["Steam Vents", Card.MINOR],
        ["Veil the Night's Hunt", Card.MINOR],
        ["Elemental Boon", Card.MINOR],
        ["Devouring Ants", Card.MINOR],
        ["Dark and Tangled Woods", Card.MINOR],
        ["Sap the Strength of Multitudes", Card.MINOR],
        ["Drift down into Slumber", Card.MINOR],
        ["Land of Haunts and Embers", Card.MINOR],
        ["Nature's Resilience", Card.MINOR],
        ["Visions of Fiery Doom", Card.MINOR],
        ["Pull Beneath the Hungry Earth", Card.MINOR],
        ["Call of the Dahan Ways", Card.MINOR],
        ["Call to Bloodshed", Card.MINOR],
        ["Call to Isolation", Card.MINOR],
        ["Call to Migrate", Card.MINOR],
        ["Call to Tend", Card.MINOR],
        ["Quicken the Earth's Struggles", Card.MINOR],
        ["Delusions of Danger", Card.MINOR],
        ["Drought", Card.MINOR],
        ["Gift of Constancy", Card.MINOR],
        ["Enticing Splendor", Card.MINOR],
        ["Entrancing Apparitions", Card.MINOR],
        ["Gift of Living Energy", Card.MINOR],
        ["Gift of Power", Card.MINOR],
        ["Gnawing Rootbiters", Card.MINOR],
        ["Lure of the Unknown", Card.MINOR],
        ["Purifying Flame", Card.MINOR],
        ["Rain of Blood", Card.MINOR],
        ["Reaching Grasp", Card.MINOR],
        ["Accelerated Rot", Card.MAJOR],
        ["Cleansing Floods", Card.MAJOR],
        ["Pillar of Living Flame", Card.MAJOR],
        ["Poisoned Land", Card.MAJOR],
        ["Terrifying Nightmares", Card.MAJOR],
        ["The Trees and Stones Speak of War", Card.MAJOR],
        ["Entwined Power", Card.MAJOR],
        ["Paralyzing Fright", Card.MAJOR],
        ["Powerstorm", Card.MAJOR],
        ["Talons of Lightning", Card.MAJOR],
        ["The Jungle Hungers", Card.MAJOR],
        ["The Land Thrashes in Furious Pain", Card.MAJOR],
        ["Tsunami", Card.MAJOR],
        ["Vigor of the Breaking Dawn", Card.MAJOR],
        ["Vengeance of the Dead", Card.MAJOR],
        ["Wrap in Wings of Sunlight", Card.MAJOR],
        ["Blazing Renewal", Card.MAJOR],
        ["Winds of Rust and Atrophy", Card.MAJOR],
        ["Indomitable Claim", Card.MAJOR],
        ["Mists of Oblivion", Card.MAJOR],
        ["Infinite Vitality", Card.MAJOR],
        ["Dissolve the Bonds of Kinship", Card.MAJOR],


        # Branch & Claw
        # Majors
        ["Strangling Firevine", Card.MAJOR],
        ["Bloodwrack Plague", Card.MAJOR],
        ["Cast down into the Briny Deep", Card.MAJOR],
        ["Death Falls Gently from Open Blossoms", Card.MAJOR],
        ["Fire and Flood", Card.MAJOR],
        ["Grant Hatred a Ravenous Form", Card.MAJOR],
        ["Insatiable Hunger of the Swarm", Card.MAJOR],
        ["Instruments of their own Ruin", Card.MAJOR],
        ["Flow like Water, Reach like Air", Card.MAJOR],
        ["Pent-Up Calamity", Card.MAJOR],
        ["Pyroclastic Flow", Card.MAJOR],
        ["Savage Transformation", Card.MAJOR],
        ["Sea Monsters", Card.MAJOR],
        ["Tigers Hunting", Card.MAJOR],
        ["Unrelenting Growth", Card.MAJOR],
        ["Volcanic Eruption", Card.MAJOR],
        ["Sweep into the Sea", Card.MAJOR],
        ["Manifest Incarnation", Card.MAJOR],
        ["Smothering Infestation", Card.MAJOR],
        ["Twisted Flowers Murmur Ultimatums", Card.MAJOR],
        ["Unlock the Gates of Deepest Power", Card.MAJOR],
        # Minor
        ["Inflame the Fires of Life", Card.MINOR],
        ["Fire in the Sky", Card.MINOR],
        ["Fleshrot Fever", Card.MINOR],
        ["Gold's Allure", Card.MINOR],
        ["Guardian Serpents", Card.MINOR],
        ["Here there be Monsters", Card.MINOR],
        ["Infested Aquifers", Card.MINOR],
        ["Poisoned Dew", Card.MINOR],
        ["Portents of Disaster", Card.MINOR],
        ["Prowling Panthers", Card.MINOR],
        ["Renewing Rain", Card.MINOR],
        ["Rites of the Land's Rejection", Card.MINOR],
        ["Pact of the Joined Hunt", Card.MINOR],
        ["Razor-Sharp Undergrowth", Card.MINOR],
        ["Growth through Sacrifice", Card.MINOR],
        ["Scour the Land", Card.MINOR],
        ["Sky Stretches to Shore", Card.MINOR],
        ["Swarming Wasps", Card.MINOR],
        ["Absorb Corruption", Card.MINOR],
        ["Animated Wrackroot", Card.MINOR],
        ["Promises of Protection", Card.MINOR],
        ["Call to Ferocity", Card.MINOR],
        ["Call to Trade", Card.MINOR],
        ["Confounding Mists", Card.MINOR],
        ["Cycles of Time and Tide", Card.MINOR],
        ["Disorienting Landscape", Card.MINOR],
        ["Elusive Ambushes", Card.MINOR],
        ["Tormenting Rotflies", Card.MINOR],
        ["Twilight Fog brings Madness", Card.MINOR],
        ["Teeming Rivers", Card.MINOR],
        ["Spur on with Words of Fire", Card.MINOR],
        # Uniques
        ["Prey on the Builders", Card.UNIQUE, "Fangs"],
        ["Teeth Gleam from Darkness", Card.UNIQUE, "Fangs"],
        ["Too near the Jungle", Card.UNIQUE, "Fangs"],
        ["Terrifying Chase", Card.UNIQUE, "Fangs"],
        ["Towering Wrath", Card.UNIQUE, "Keeper"],
        ["Regrow from Roots", Card.UNIQUE, "Keeper"],
        ["Boon of Growing Power", Card.UNIQUE, "Keeper"],
        ["Sacrosanct Wilderness", Card.UNIQUE, "Keeper"],

        # Promo
        # Uniques
        ["Flash-Fires", Card.UNIQUE, "Wildfire"],
        ["Asphyxiating Smoke", Card.UNIQUE, "Wildfire"],
        ["Flame's Fury", Card.UNIQUE, "Wildfire"],
        ["Threatening Flames", Card.UNIQUE, "Wildfire"],
        ["Gift of the Primordial Deeps", Card.UNIQUE, "Serpent"],
        ["Gift of Flowing Power", Card.UNIQUE, "Serpent"],
        ["Absorb Essence", Card.UNIQUE, "Serpent"],
        ["Elemental Aegis", Card.UNIQUE, "Serpent"],

        # Jagged Earth
        # Major
        ["Forests of Living Obsidian", Card.MAJOR],
        ["Infestation of Venomous Spiders", Card.MAJOR],
        ["Dream of the Untouched Land", Card.MAJOR],
        ["Angry Bears", Card.MAJOR],
        ["Focus the Land's Anguish", Card.MAJOR],
        ["Vanish Softly Away, Forgotten by All", Card.MAJOR],
        ["Unleash a Torrent of the Self's Own Essence", Card.MAJOR],
        ["Bargains of Power and Protection", Card.MAJOR],
        ["Transform to a Murderous Darkness", Card.MAJOR],
        ["Settle Into Hunting-Grounds", Card.MAJOR],
        ["Walls of Rock and Thorn", Card.MAJOR],
        ["Voice of Command", Card.MAJOR],
        ["Irresistible Call", Card.MAJOR],
        ["The Wounded Wild Turns on its Assailants", Card.MAJOR],
        ["Draw Towards a Consuming Void", Card.MAJOR],
        ["Storm-Swath", Card.MAJOR],
        ["Spill Bitterness into the Earth", Card.MAJOR],
        ["Utter a Curse of Dread and Bone", Card.MAJOR],
        ["Sleep and Never Waken", Card.MAJOR],
        ["Weave Together the Fabric of Place", Card.MAJOR],
        ["Trees Radiate Celestial Brilliance", Card.MAJOR],
        ["Thickets Erupt with Every Touch of Breeze", Card.MAJOR],
        ["Melt Earth into Quicksand", Card.MAJOR],
        # Minor
        ["Hazards Spread Across The Island", Card.MINOR],
        ["Bats Scout For Raids By Darkness", Card.MINOR],
        ["Birds Cry Warning", Card.MINOR],
        ["Blood Draws Predators", Card.MINOR],
        ["Carapaced Land", Card.MINOR],
        ["Call To Guard", Card.MINOR],
        ["Desiccating Winds", Card.MINOR],
        ["Dry Wood Explodes In Smoldering Splinters", Card.MINOR],
        ["Gift of Nature's Connection", Card.MINOR],
        ["Entrap The Forces Of Corruption", Card.MINOR],
        ["Domesticated Animals Go Berserk", Card.MINOR],
        ["Dire Metamorphosis", Card.MINOR],
        ["Skies Herald The Season Of Return", Card.MINOR],
        ["Gift of Twinned Days", Card.MINOR],
        ["Haunted By Primal Memories", Card.MINOR],
        ["Like Calls to Like", Card.MINOR],
        ["Unquenchable Flames", Card.MINOR],
        ["Mesmerized Tranquility", Card.MINOR],
        ["Territorial Strife", Card.MINOR],
        ["Renewing Boon", Card.MINOR],
        ["Scream Disease Into The Wind", Card.MINOR],
        ["Sear Anger Into The Wild Lands", Card.MINOR],
        ["Set Them On An Ever-Twisting Trail", Card.MINOR],
        ["Strong And Constant Currents", Card.MINOR],
        ["Sucking Ooze", Card.MINOR],
        ["Sunset's Fire Flows Across The Land", Card.MINOR],
        ["Terror Turns To Madness", Card.MINOR],
        ["The Shore Seethes With Hatred", Card.MINOR],
        ["Thriving Chokefungus", Card.MINOR],
        ["Treacherous Waterways", Card.MINOR],
        ["Flow Downriver, Blow Downwind", Card.MINOR],
        ["Weep For What Is Lost", Card.MINOR],
        ["Favor Of The Sun And Star-Lit Dark", Card.MINOR],
        # Uniques
        ["Unexpected Tigers", Card.UNIQUE, "Trickster"],
        ["Impersonate Authority", Card.UNIQUE, "Trickster"],
        ["Incite the Mob", Card.UNIQUE, "Trickster"],
        ["Overenthusiastic Arson", Card.UNIQUE, "Trickster"],
        ["Rain of Ash", Card.UNIQUE, "Volcano"],
        ["Lava Flows", Card.UNIQUE, "Volcano"],
        ["Exaltation of Molten Stone", Card.UNIQUE, "Volcano"],
        ["Pyroclastic Bombardment", Card.UNIQUE, "Volcano"],
        ["Dissolving Vapors", Card.UNIQUE, "Mist"],
        ["The Fog Closes In", Card.UNIQUE, "Mist"],
        ["Unnerving Pall", Card.UNIQUE, "Mist"],
        ["Flowing and Silent Forms Dart By", Card.UNIQUE, "Mist"],
        ["Fiery Vengeance", Card.UNIQUE, "Vengeance"],
        ["Plaguebearers", Card.UNIQUE, "Vengeance"],
        ["Fetid Breath Spreads Infection", Card.UNIQUE, "Vengeance"],
        ["Strike Low with Sudden Fevers", Card.UNIQUE, "Vengeance"],
        ["Absolute Stasis", Card.UNIQUE, "Fractured"],
        ["Pour Time Sideways", Card.UNIQUE, "Fractured"],
        ["The Past Returns Again", Card.UNIQUE, "Fractured"],
        ["Blur the Arc of Years", Card.UNIQUE, "Fractured"],
        ["Boon of Ancient Memories", Card.UNIQUE, "Shifting"],
        ["Elemental Teachings", Card.UNIQUE, "Shifting"],
        ["Share Secrets of Survival", Card.UNIQUE, "Shifting"],
        ["Study the Invaders' Fears", Card.UNIQUE, "Shifting"],
        ["Boon of Reimagining", Card.UNIQUE, "Starlight"],
        ["Gather the Scattered Light of Stars", Card.UNIQUE, "Starlight"],
        ["Shape the Self Anew", Card.UNIQUE, "Starlight"],
        ["Peace of the Nighttime Sky", Card.UNIQUE, "Starlight"],
        ["Scarred and Stony Land", Card.UNIQUE, "Stone"],
        ["Plows Shatter on Rocky Ground", Card.UNIQUE, "Stone"],
        ["Jagged Shards Push from the Earth", Card.UNIQUE, "Stone"],
        ["Stubborn Solidity", Card.UNIQUE, "Stone"],
        ["Perils of the Deepest Island", Card.UNIQUE, "Lure"],
        ["Softly Beckon Ever Inward", Card.UNIQUE, "Lure"],
        ["Gift of the Untamed Wild", Card.UNIQUE, "Lure"],
        ["Swallowed by the Wilderness", Card.UNIQUE, "Lure"],
        ["Pursue with Scratches, Pecks, and Stings", Card.UNIQUE, "Minds"],
        ["A Dreadful Tide of Scurrying Flesh", Card.UNIQUE, "Minds"],
        ["Boon of Swarming Bedevilment", Card.UNIQUE, "Minds"],
        ["Guide the Way on Feathered Wings", Card.UNIQUE, "Minds"],
        ["Ever-Multiplying Swarm", Card.UNIQUE, "Minds"],

        # Promo2
        # Uniques
        ["Foundations Sink into Mud", Card.UNIQUE, "Downpour"],
        ["Gift of Abundance", Card.UNIQUE, "Downpour"],
        ["Unbearable Deluge", Card.UNIQUE, "Downpour"],
        ["Dark Skies Loose a Stinging Rain", Card.UNIQUE, "Downpour"],
        ["Traveler's Boon", Card.UNIQUE, "Finder"],
        ["Offer Passage Between Worlds", Card.UNIQUE, "Finder"],
        ["Aid from the Spirit-Speakers", Card.UNIQUE, "Finder"],
        ["Paths Tied by Nature", Card.UNIQUE, "Finder"],
        ["Ways of Shore and Heartland", Card.UNIQUE, "Finder"],
        ["A Circuitous and Wending Journey", Card.UNIQUE, "Finder"],

)

class Command(BaseCommand):
    help = 'Seed the database'

    def add_arguments(self, parser):
        # parser.add_argument('poll_ids', nargs='+', type=int)
        pass

    @transaction.atomic
    def handle(self, *args, **options):
        for s in spirits:
            Spirit(name=s[0]).save()
        for c in cards:
            try:
                Card(name=c[0], type=c[1], spirit=Spirit.objects.get(name=c[2])).save()
            except:
                Card(name=c[0], type=c[1]).save()

        if settings.DEBUG:
            User.objects.create_superuser(username='admin', password='admin').save()

        g = Game(name='My Game')
        g.save()
        g.minor_deck.set(Card.objects.filter(type=Card.MINOR))
        g.major_deck.set(Card.objects.filter(type=Card.MAJOR))

        gp = GamePlayer(game=g, spirit=Spirit.objects.get(name='Finder'), notes="You can add notes here...\ntop:1 bottom:1")
        gp.save()
        gp.hand.set(Card.objects.filter(spirit=Spirit.objects.get(name='Finder')))

        gp = GamePlayer(game=g, spirit=Spirit.objects.get(name='Stone'))
        gp.save()
        gp.hand.set(Card.objects.filter(spirit=Spirit.objects.get(name='Stone')))

        self.stdout.write(self.style.SUCCESS('Seeded database'))
