import datetime
from django.core.management.base import BaseCommand, CommandError
from django.contrib.auth.models import User
from django.conf import settings
from django.db import transaction
from pbf.models import *

spirits = (
        ["Bringer"],
        ["Exploratory Bringer"],
        ["Downpour"],
        ["Earth"],
        ["Fangs"],
        ["Finder"],
        ["Fractured"],
        ["Green"],
        ["Keeper"],
        ["Lightning"],
        ["Lure"],
        ["Minds"],
        ["Mist"],
        ["Ocean"],
        ["River"],
        ["Serpent"],
        ["Shadows"],
        ["Shifting"],
        ["Starlight"],
        ["Stone"],
        ["Thunderspeaker"],
        ["Trickster"],
        ["Vengeance"],
        ["Volcano"],
        ["Wildfire"],
)

cards = (
        # Spirit Cards
        ["Lightning", "Shatter Homesteads", 2, [Elements.Fire, Elements.Air]],
        ["Lightning", "Raging Storm", 3, [Elements.Fire, Elements.Air, Elements.Water]],
        ["Lightning", "Lightning's Boon", 1, [Elements.Fire, Elements.Air]],
        ["Lightning", "Harbingers of the Lightning", 0, [Elements.Fire, Elements.Air]],
        ["River", "Flash Floods", 2, [Elements.Sun, Elements.Water]],
        ["River", "Wash Away", 1, [Elements.Water, Elements.Earth]],
        ["River", "Boon of Vigor", 0, [Elements.Sun, Elements.Water, Elements.Plant]],
        ["River", "River's Bounty", 0, [Elements.Sun, Elements.Water, Elements.Animal]],
        ["Shadows", "Concealing Shadows", 0, [Elements.Moon, Elements.Air]],
        ["Shadows", "Favors Called Due", 1, [Elements.Moon, Elements.Air, Elements.Animal]],
        ["Shadows", "Mantle of Dread", 1, [Elements.Moon, Elements.Fire, Elements.Air]],
        ["Shadows", "Crops Wither and Fade", 1, [Elements.Moon, Elements.Fire, Elements.Plant]],
        ["Earth", "Guard the Healing Land", 3, [Elements.Water, Elements.Earth, Elements.Plant]],
        ["Earth", "A Year of Perfect Stillness", 3, [Elements.Sun, Elements.Earth]],
        ["Earth", "Rituals of Destruction", 3, [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Earth, Elements.Plant]],
        ["Earth", "Draw of the Fruitful Earth", 1, [Elements.Earth, Elements.Plant, Elements.Animal]],
        ["Thunderspeaker", "Manifestation of Power and Glory", 3, [Elements.Sun, Elements.Fire, Elements.Air]],
        ["Thunderspeaker", "Words of Warning", 1, [Elements.Sun, Elements.Air, Elements.Animal]],
        ["Thunderspeaker", "Sudden Ambush", 2, [Elements.Fire, Elements.Air, Elements.Animal]],
        ["Thunderspeaker", "Voice of Thunder", 0, [Elements.Sun, Elements.Air]],
        ["Ocean", "Call of the Deeps", 0, [Elements.Moon, Elements.Air, Elements.Water]],
        ["Ocean", "Grasping Tide", 1, [Elements.Moon, Elements.Water]],
        ["Ocean", "Swallow the Land-Dwellers", 0, [Elements.Water, Elements.Earth]],
        ["Ocean", "Tidal Boon", 1, [Elements.Moon, Elements.Water, Elements.Earth]],
        ["Bringer", "Predatory Nightmares", 2, [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Animal]],
        ["Bringer", "Dread Apparitions", 2, [Elements.Moon, Elements.Air]],
        ["Bringer", "Call on Midnight's Dream", 0, [Elements.Moon, Elements.Animal]],
        ["Bringer", "Dreams of the Dahan", 0, [Elements.Moon, Elements.Air]],
        ["Green", "Overgrow in a Night", 2, [Elements.Moon, Elements.Plant]],
        ["Green", "Gift of Proliferation", 1, [Elements.Moon, Elements.Plant]],
        ["Green", "Fields Choked with Growth", 0, [Elements.Sun, Elements.Water, Elements.Plant]],
        ["Green", "Stem the Flow of Fresh Water", 0, [Elements.Water, Elements.Plant]],

        # Colored Corners,
        # green corner,
        [Card.MINOR, "Savage Mawbeasts", 0, [Elements.Fire, Elements.Animal]],
        [Card.MINOR, "Voracious Growth", 1, [Elements.Water, Elements.Plant]],
        [Card.MINOR, "Rouse the Trees and Stones", 1, [Elements.Fire, Elements.Earth, Elements.Plant]],
        # blue corner,
        [Card.MINOR, "Encompassing Ward", 1, [Elements.Sun, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Song of Sanctity", 1, [Elements.Sun, Elements.Water, Elements.Plant]],
        [Card.MINOR, "Uncanny Melting", 1, [Elements.Sun, Elements.Moon, Elements.Water]],
        # red corner,
        [Card.MINOR, "Shadows of the Burning Forest", 0, [Elements.Moon, Elements.Fire, Elements.Plant]],

        # Minors inside color cornered block,
        [Card.MINOR, "Steam Vents", 1, [Elements.Fire, Elements.Air, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Veil the Night's Hunt", 1, [Elements.Moon, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Elemental Boon", 1, []],

        # Second Badge,
        # Minors,
        [Card.MINOR, "Devouring Ants", 1, [Elements.Sun, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Dark and Tangled Woods", 1, [Elements.Moon, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Sap the Strength of Multitudes", 0, [Elements.Water, Elements.Animal]],
        [Card.MINOR, "Drift down into Slumber", 0, [Elements.Air, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Land of Haunts and Embers", 0, [Elements.Moon, Elements.Fire, Elements.Air]],
        [Card.MINOR, "Nature's Resilience", 1, [Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Visions of Fiery Doom", 1, [Elements.Moon, Elements.Fire]],
        [Card.MINOR, "Pull Beneath the Hungry Earth", 1, [Elements.Moon, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Call of the Dahan Ways", 1, [Elements.Moon, Elements.Water, Elements.Animal]],
        [Card.MINOR, "Call to Bloodshed", 1, [Elements.Sun, Elements.Fire, Elements.Animal]],
        [Card.MINOR, "Call to Isolation", 0, [Elements.Sun, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Call to Migrate", 1, [Elements.Fire, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Call to Tend", 1, [Elements.Water, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Quicken the Earth's Struggles", 1, [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Delusions of Danger", 1, [Elements.Sun, Elements.Moon, Elements.Air]],
        [Card.MINOR, "Drought", 1, [Elements.Sun, Elements.Fire, Elements.Earth]],
        [Card.MINOR, "Gift of Constancy", 0, [Elements.Sun, Elements.Earth]],
        [Card.MINOR, "Enticing Splendor", 0, [Elements.Sun, Elements.Air, Elements.Plant]],
        [Card.MINOR, "Entrancing Apparitions", 1, [Elements.Moon, Elements.Air, Elements.Water]],
        [Card.MINOR, "Gift of Living Energy", 0, [Elements.Sun, Elements.Fire, Elements.Plant]],
        [Card.MINOR, "Gift of Power", 0, [Elements.Moon, Elements.Water, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Gnawing Rootbiters", 0, [Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Lure of the Unknown", 0, [Elements.Moon, Elements.Fire, Elements.Air, Elements.Plant]],
        [Card.MINOR, "Purifying Flame", 1, [Elements.Sun, Elements.Fire, Elements.Air, Elements.Plant]],
        [Card.MINOR, "Rain of Blood", 0, [Elements.Air, Elements.Water, Elements.Animal]],
        [Card.MINOR, "Reaching Grasp", 0, [Elements.Sun, Elements.Air, Elements.Water]],
        # Majors,
        [Card.MAJOR, "Accelerated Rot", 4, [Elements.Sun, Elements.Water, Elements.Plant]],
        [Card.MAJOR, "Cleansing Floods", 5, [Elements.Sun, Elements.Water]],
        [Card.MAJOR, "Pillar of Living Flame", 5, [Elements.Fire]],
        [Card.MAJOR, "Poisoned Land", 3, [Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Terrifying Nightmares", 4, [Elements.Moon, Elements.Air]],
        [Card.MAJOR, "The Trees and Stones Speak of War", 2, [Elements.Sun, Elements.Earth, Elements.Plant]],
        [Card.MAJOR, "Entwined Power", 2, [Elements.Moon, Elements.Water, Elements.Plant]],
        [Card.MAJOR, "Paralyzing Fright", 4, [Elements.Air, Elements.Earth]],
        [Card.MAJOR, "Powerstorm", 3, [Elements.Sun, Elements.Fire, Elements.Air]],
        [Card.MAJOR, "Talons of Lightning", 6, [Elements.Fire, Elements.Air]],
        [Card.MAJOR, "The Jungle Hungers", 3, [Elements.Moon, Elements.Plant]],
        [Card.MAJOR, "The Land Thrashes in Furious Pain", 4, [Elements.Moon, Elements.Fire, Elements.Earth]],
        [Card.MAJOR, "Tsunami", 6, [Elements.Water, Elements.Earth]],
        [Card.MAJOR, "Vigor of the Breaking Dawn", 3, [Elements.Sun, Elements.Animal]],
        [Card.MAJOR, "Vengeance of the Dead", 3, [Elements.Moon, Elements.Fire, Elements.Animal]],
        [Card.MAJOR, "Wrap in Wings of Sunlight", 3, [Elements.Sun, Elements.Air, Elements.Animal]],
        [Card.MAJOR, "Blazing Renewal", 5, [Elements.Fire, Elements.Earth, Elements.Plant]],
        [Card.MAJOR, "Winds of Rust and Atrophy", 3, [Elements.Air, Elements.Water, Elements.Animal]],
        [Card.MAJOR, "Indomitable Claim", 4, [Elements.Sun, Elements.Earth]],
        [Card.MAJOR, "Mists of Oblivion", 4, [Elements.Moon, Elements.Air, Elements.Water]],
        [Card.MAJOR, "Infinite Vitality", 3, [Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Dissolve the Bonds of Kinship", 4, [Elements.Fire, Elements.Water, Elements.Animal]],

        # Branch & Claw,
        # Majors,
        [Card.MAJOR, "Strangling Firevine", 4, [Elements.Fire, Elements.Plant]],
        [Card.MAJOR, "Bloodwrack Plague", 4, [Elements.Water, Elements.Earth, Elements.Animal]],
        [Card.MAJOR, "Cast down into the Briny Deep", 9, [Elements.Sun, Elements.Moon, Elements.Water, Elements.Earth]],
        [Card.MAJOR, "Death Falls Gently from Open Blossoms", 4, [Elements.Moon, Elements.Air, Elements.Plant]],
        [Card.MAJOR, "Fire and Flood", 7, [Elements.Sun, Elements.Fire, Elements.Water]],
        [Card.MAJOR, "Grant Hatred a Ravenous Form", 4, [Elements.Moon, Elements.Fire]],
        [Card.MAJOR, "Insatiable Hunger of the Swarm", 4, [Elements.Air, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Instruments of their own Ruin", 4, [Elements.Sun, Elements.Fire, Elements.Air, Elements.Animal]],
        [Card.MAJOR, "Flow like Water, Reach like Air", 2, [Elements.Air, Elements.Water]],
        [Card.MAJOR, "Pent-Up Calamity", 3, [Elements.Moon, Elements.Fire, Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Pyroclastic Flow", 3, [Elements.Fire, Elements.Air, Elements.Earth]],
        [Card.MAJOR, "Savage Transformation", 2, [Elements.Moon, Elements.Animal]],
        [Card.MAJOR, "Sea Monsters", 5, [Elements.Water, Elements.Animal]],
        [Card.MAJOR, "Tigers Hunting", 2, [Elements.Sun, Elements.Moon, Elements.Animal]],
        [Card.MAJOR, "Unrelenting Growth", 4, [Elements.Sun, Elements.Fire, Elements.Water, Elements.Plant]],
        [Card.MAJOR, "Volcanic Eruption", 8, [Elements.Fire, Elements.Earth]],
        [Card.MAJOR, "Sweep into the Sea", 4, [Elements.Sun, Elements.Air, Elements.Water]],
        [Card.MAJOR, "Manifest Incarnation", 6, [Elements.Sun, Elements.Moon, Elements.Earth, Elements.Animal]],
        [Card.MAJOR, "Smothering Infestation", 3, [Elements.Water, Elements.Plant]],
        [Card.MAJOR, "Twisted Flowers Murmur Ultimatums", 5, [Elements.Sun, Elements.Moon, Elements.Air, Elements.Earth, Elements.Plant]],
        [Card.MAJOR, "Unlock the Gates of Deepest Power", 4, [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Air, Elements.Water, Elements.Earth, Elements.Plant, Elements.Animal]],
        # Minor,
        [Card.MINOR, "Inflame the Fires of Life", 1, [Elements.Moon, Elements.Fire, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Fire in the Sky", 1, [Elements.Sun, Elements.Fire, Elements.Air]],
        [Card.MINOR, "Fleshrot Fever", 1, [Elements.Fire, Elements.Air, Elements.Water, Elements.Animal]],
        [Card.MINOR, "Gold's Allure", 0, [Elements.Fire, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Guardian Serpents", 1, [Elements.Sun, Elements.Moon, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Here there be Monsters", 0, [Elements.Moon, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Infested Aquifers", 1, [Elements.Moon, Elements.Water, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Poisoned Dew", 1, [Elements.Fire, Elements.Water, Elements.Plant]],
        [Card.MINOR, "Portents of Disaster", 0, [Elements.Sun, Elements.Moon, Elements.Air]],
        [Card.MINOR, "Prowling Panthers", 1, [Elements.Moon, Elements.Fire   , Elements.Animal]],
        [Card.MINOR, "Renewing Rain", 1, [Elements.Water, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Rites of the Land's Rejection", 1, [Elements.Moon, Elements.Fire, Elements.Earth]],
        [Card.MINOR, "Pact of the Joined Hunt", 1, [Elements.Sun, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Razor-Sharp Undergrowth", 1, [Elements.Moon, Elements.Plant]],
        [Card.MINOR, "Growth through Sacrifice", 0, [Elements.Moon, Elements.Fire, Elements.Water, Elements.Plant]],
        [Card.MINOR, "Scour the Land", 1, [Elements.Air, Elements.Earth]],
        [Card.MINOR, "Sky Stretches to Shore", 1, [Elements.Sun, Elements.Air, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Swarming Wasps", 0, [Elements.Fire, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Absorb Corruption", 1, [Elements.Sun, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Animated Wrackroot", 0, [Elements.Moon, Elements.Fire, Elements.Plant]],
        [Card.MINOR, "Promises of Protection", 0, [Elements.Sun, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Call to Ferocity", 0, [Elements.Sun, Elements.Fire, Elements.Earth]],
        [Card.MINOR, "Call to Trade", 1, [Elements.Air, Elements.Water, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Confounding Mists", 1, [Elements.Air, Elements.Water]],
        [Card.MINOR, "Cycles of Time and Tide", 1, [Elements.Sun, Elements.Moon, Elements.Water]],
        [Card.MINOR, "Disorienting Landscape", 1, [Elements.Moon, Elements.Air, Elements.Plant]],
        [Card.MINOR, "Elusive Ambushes", 1, [Elements.Sun, Elements.Fire, Elements.Water]],
        [Card.MINOR, "Tormenting Rotflies", 1, [Elements.Air, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Twilight Fog brings Madness", 0, [Elements.Sun, Elements.Moon, Elements.Air, Elements.Water]],
        [Card.MINOR, "Teeming Rivers", 1, [Elements.Sun, Elements.Water, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Spur on with Words of Fire", 1, [Elements.Sun, Elements.Fire, Elements.Air]],
        # Uniques,
        ["Fangs", "Prey on the Builders", 1, [Elements.Moon, Elements.Fire, Elements.Animal]],
        ["Fangs", "Teeth Gleam from Darkness", 1, [Elements.Moon, Elements.Plant, Elements.Animal]],
        ["Fangs", "Too near the Jungle", 0, [Elements.Plant, Elements.Animal]],
        ["Fangs", "Terrifying Chase", 1, [Elements.Sun, Elements.Animal]],
        ["Keeper", "Towering Wrath", 3, [Elements.Sun, Elements.Fire, Elements.Plant]],
        ["Keeper", "Regrow from Roots", 1, [Elements.Water, Elements.Earth, Elements.Plant]],
        ["Keeper", "Boon of Growing Power", 1, [Elements.Sun, Elements.Moon, Elements.Plant]],
        ["Keeper", "Sacrosanct Wilderness", 2, [Elements.Sun, Elements.Earth, Elements.Plant]],

        # Promo,
        # Uniques,
        ["Wildfire", "Flash-Fires", 2, [Elements.Fire, Elements.Air]],
        ["Wildfire", "Asphyxiating Smoke", 2, [Elements.Fire, Elements.Air, Elements.Plant]],
        ["Wildfire", "Flame's Fury", 0, [Elements.Sun, Elements.Fire, Elements.Plant]],
        ["Wildfire", "Threatening Flames", 0, [Elements.Fire, Elements.Plant]],
        ["Serpent", "Gift of the Primordial Deeps", 1, [Elements.Moon, Elements.Earth]],
        ["Serpent", "Gift of Flowing Power", 1, [Elements.Fire, Elements.Water]],
        ["Serpent", "Absorb Essence", 2, [Elements.Moon, Elements.Fire, Elements.Water, Elements.Earth]],
        ["Serpent", "Elemental Aegis", 1, [Elements.Fire, Elements.Water, Elements.Earth]],

        # Jagged Earth,
        # Major,
        [Card.MAJOR, "Forests of Living Obsidian", 4, [Elements.Sun, Elements.Fire, Elements.Earth, Elements.Plant]],
        [Card.MAJOR, "Infestation of Venomous Spiders", 4, [Elements.Air, Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Dream of the Untouched Land", 6, [Elements.Moon, Elements.Water, Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Angry Bears", 3, [Elements.Sun, Elements.Fire, Elements.Animal]],
        [Card.MAJOR, "Focus the Land's Anguish", 5, [Elements.Sun]],
        [Card.MAJOR, "Vanish Softly Away, Forgotten by All", 3, [Elements.Moon, Elements.Air]],
        [Card.MAJOR, "Unleash a Torrent of the Self's Own Essence", 2, [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Water]],
        [Card.MAJOR, "Bargains of Power and Protection", 2, [Elements.Sun, Elements.Water, Elements.Earth, Elements.Animal]],
        [Card.MAJOR, "Transform to a Murderous Darkness", 6, [Elements.Moon, Elements.Fire, Elements.Air, Elements.Water, Elements.Plant]],
        [Card.MAJOR, "Settle Into Hunting-Grounds", 3, [Elements.Moon, Elements.Fire, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Walls of Rock and Thorn", 4, [Elements.Sun, Elements.Earth, Elements.Plant]],
        [Card.MAJOR, "Voice of Command", 3, [Elements.Sun, Elements.Air]],
        [Card.MAJOR, "Irresistible Call", 6, [Elements.Sun, Elements.Air, Elements.Plant]],
        [Card.MAJOR, "The Wounded Wild Turns on its Assailants", 4, [Elements.Fire, Elements.Plant, Elements.Animal]],
        [Card.MAJOR, "Draw Towards a Consuming Void", 8, []],
        [Card.MAJOR, "Storm-Swath", 3, [Elements.Fire, Elements.Air, Elements.Water]],
        [Card.MAJOR, "Spill Bitterness into the Earth", 5, [Elements.Fire, Elements.Water, Elements.Earth]],
        [Card.MAJOR, "Utter a Curse of Dread and Bone", 4, [Elements.Moon, Elements.Animal]],
        [Card.MAJOR, "Sleep and Never Waken", 3, [Elements.Moon, Elements.Air, Elements.Earth, Elements.Animal]],
        [Card.MAJOR, "Weave Together the Fabric of Place", 4, [Elements.Sun, Elements.Moon, Elements.Air, Elements.Water, Elements.Earth]],
        [Card.MAJOR, "Trees Radiate Celestial Brilliance", 3, [Elements.Sun, Elements.Moon, Elements.Plant]],
        [Card.MAJOR, "Thickets Erupt with Every Touch of Breeze", 3, [Elements.Air, Elements.Plant]],
        [Card.MAJOR, "Melt Earth into Quicksand", 4, [Elements.Moon, Elements.Water, Elements.Earth]],
        # Minor,
        [Card.MINOR, "Hazards Spread Across The Island", 0, [Elements.Fire, Elements.Air, Elements.Earth, Elements.Plant ]],
        [Card.MINOR, "Bats Scout For Raids By Darkness", 1, [Elements.Moon, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Birds Cry Warning", 1, [Elements.Sun, Elements.Air, Elements.Animal]],
        [Card.MINOR, "Blood Draws Predators", 1, [Elements.Sun, Elements.Fire, Elements.Water, Elements.Animal]],
        [Card.MINOR, "Carapaced Land", 0, [Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Call To Guard", 0, [Elements.Sun, Elements.Air, Elements.Earth]],
        [Card.MINOR, "Desiccating Winds", 1, [Elements.Fire, Elements.Air, Elements.Earth]],
        [Card.MINOR, "Dry Wood Explodes In Smoldering Splinters", 1, [Elements.Fire, Elements.Air, Elements.Plant]],
        [Card.MINOR, "Gift of Nature's Connection", 0, []],
        [Card.MINOR, "Entrap The Forces Of Corruption", 1, [Elements.Earth, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Domesticated Animals Go Berserk", 1, [Elements.Moon, Elements.Fire, Elements.Animal]],
        [Card.MINOR, "Dire Metamorphosis", 1, [Elements.Moon, Elements.Air, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Skies Herald The Season Of Return", 1, [Elements.Sun, Elements.Moon, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Gift of Twinned Days", 1, [Elements.Sun, Elements.Moon]],
        [Card.MINOR, "Haunted By Primal Memories", 1, [Elements.Moon, Elements.Air, Elements. Earth]],
        [Card.MINOR, "Like Calls to Like", 1, [Elements.Sun, Elements.Water, Elements.Plant]],
        [Card.MINOR, "Unquenchable Flames", 1, [Elements.Moon, Elements.Fire, Elements.Earth]],
        [Card.MINOR, "Mesmerized Tranquility", 0, [Elements.Water, Elements.Earth, Elements.Animal]],
        [Card.MINOR, "Territorial Strife", 0, [Elements.Sun, Elements.Fire, Elements.Animal]],
        [Card.MINOR, "Renewing Boon", 1, [Elements.Sun, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Scream Disease Into The Wind", 1, [Elements.Air, Elements.Water, Elements.Animal]],
        [Card.MINOR, "Sear Anger Into The Wild Lands", 0, [Elements.Sun, Elements.Fire, Elements.Plant]],
        [Card.MINOR, "Set Them On An Ever-Twisting Trail", 1, [Elements.Air, Elements.Plant, Elements.Animal]],
        [Card.MINOR, "Strong And Constant Currents", 0, [Elements.Sun, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Sucking Ooze", 0, [Elements.Moon, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Sunset's Fire Flows Across The Land", 1, [Elements.Sun, Elements.Moon, Elements.Fire, Elements.Water]],
        [Card.MINOR, "Terror Turns To Madness", 0, [Elements.Moon, Elements.Air, Elements.Water]],
        [Card.MINOR, "The Shore Seethes With Hatred", 1, [Elements.Fire, Elements.Water, Elements.Earth, Elements.Plant]],
        [Card.MINOR, "Thriving Chokefungus", 1, [Elements.Moon, Elements.Water, Elements.Plant]],
        [Card.MINOR, "Treacherous Waterways", 0, [Elements.Fire, Elements.Water, Elements.Earth]],
        [Card.MINOR, "Flow Downriver, Blow Downwind", 0, [Elements.Air, Elements.Water, Elements.Plant]],
        [Card.MINOR, "Weep For What Is Lost", 0, [Elements.Fire, Elements.Water, Elements.Animal]],
        [Card.MINOR, "Favor Of The Sun And Star-Lit Dark", 1, [Elements.Sun, Elements.Moon, Elements.Plant]],
        # Uniques,
        ["Trickster", "Unexpected Tigers", 0, [Elements.Moon, Elements.Fire, Elements.Animal]],
        ["Trickster", "Impersonate Authority", 0, [Elements.Sun, Elements.Air, Elements.Animal]],
        ["Trickster", "Incite the Mob", 1, [Elements.Moon, Elements.Fire, Elements.Air]],
        ["Trickster", "Overenthusiastic Arson", 1, [Elements.Fire, Elements.Air]],
        ["Volcano", "Rain of Ash", 2, [Elements.Fire, Elements.Air, Elements.Earth]],
        ["Volcano", "Lava Flows", 1, [Elements.Fire, Elements.Earth]],
        ["Volcano", "Exaltation of Molten Stone", 1, [Elements.Moon, Elements.Fire, Elements.Earth]],
        ["Volcano", "Pyroclastic Bombardment", 3, [Elements.Fire, Elements.Air, Elements.Earth]],
        ["Mist", "Dissolving Vapors", 2, [Elements.Air, Elements.Water]],
        ["Mist", "The Fog Closes In", 1, [Elements.Moon, Elements.Air, Elements.Water]],
        ["Mist", "Unnerving Pall", 1, [Elements.Moon, Elements.Air, Elements.Animal]],
        ["Mist", "Flowing and Silent Forms Dart By", 0, [Elements.Moon, Elements.Air, Elements.Water]],
        ["Vengeance", "Fiery Vengeance", 0, [Elements.Sun, Elements.Fire]],
        ["Vengeance", "Plaguebearers", 1, [Elements.Fire, Elements.Water, Elements.Animal]],
        ["Vengeance", "Fetid Breath Spreads Infection", 2, [Elements.Air, Elements.Water, Elements.Animal]],
        ["Vengeance", "Strike Low with Sudden Fevers", 2, [Elements.Fire, Elements.Air, Elements.Earth, Elements.Animal]],
        ["Fractured", "Absolute Stasis", 1, [Elements.Sun, Elements.Air, Elements.Earth]],
        ["Fractured", "Pour Time Sideways", 1, [Elements.Moon, Elements.Air, Elements.Water]],
        ["Fractured", "The Past Returns Again", 0, [Elements.Sun, Elements.Moon]],
        ["Fractured", "Blur the Arc of Years", 1, [Elements.Sun, Elements.Moon, Elements.Air]],
        ["Shifting", "Boon of Ancient Memories", 1, [Elements.Moon, Elements.Water, Elements.Earth, Elements.Plant]],
        ["Shifting", "Elemental Teachings", 0, [Elements.Moon, Elements.Air, Elements.Earth]],
        ["Shifting", "Share Secrets of Survival", 0, [Elements.Sun, Elements.Air, Elements.Earth]],
        ["Shifting", "Study the Invaders' Fears", 0, [Elements.Moon, Elements.Air, Elements.Animal]],
        ["Starlight", "Boon of Reimagining", 1, [Elements.Moon]],
        ["Starlight", "Gather the Scattered Light of Stars", 0, [Elements.Moon]],
        ["Starlight", "Shape the Self Anew", 0, [Elements.Moon]],
        ["Starlight", "Peace of the Nighttime Sky", 1, [Elements.Moon]],
        ["Stone", "Scarred and Stony Land", 2, [Elements.Moon, Elements.Earth]],
        ["Stone", "Plows Shatter on Rocky Ground", 2, [Elements.Earth]],
        ["Stone", "Jagged Shards Push from the Earth", 0, [Elements.Fire, Elements.Earth]],
        ["Stone", "Stubborn Solidity", 1, [Elements.Sun, Elements.Earth, Elements.Animal]],
        ["Lure", "Perils of the Deepest Island", 1, [Elements.Moon, Elements.Plant, Elements.Animal]],
        ["Lure", "Softly Beckon Ever Inward", 2, [Elements.Moon, Elements.Air]],
        ["Lure", "Gift of the Untamed Wild", 0, [Elements.Moon, Elements.Fire, Elements.Air, Elements.Plant]],
        ["Lure", "Swallowed by the Wilderness", 1, [Elements.Fire, Elements.Air, Elements.Plant, Elements.Animal]],
        ["Minds", "Pursue with Scratches, Pecks, and Stings", 0, [Elements.Sun, Elements.Fire, Elements.Air, Elements.Animal]],
        ["Minds", "A Dreadful Tide of Scurrying Flesh", 0, [Elements.Moon, Elements.Air, Elements.Water, Elements.Animal]],
        ["Minds", "Boon of Swarming Bedevilment", 0, [Elements.Air, Elements.Water, Elements.Animal]],
        ["Minds", "Guide the Way on Feathered Wings", 0, [Elements.Sun, Elements.Air, Elements.Animal]],
        ["Minds", "Ever-Multiplying Swarm", 1, [Elements.Fire, Elements.Earth, Elements.Animal]],

        # Promo2,
        # Uniques,
        ["Downpour", "Foundations Sink into Mud", 1, [Elements.Water, Elements.Earth]],
        ["Downpour", "Gift of Abundance", 1, [Elements.Sun, Elements.Air, Elements.Water, Elements.Plant]],
        ["Downpour", "Unbearable Deluge", 0, [Elements.Air, Elements.Water, Elements.Earth]],
        ["Downpour", "Dark Skies Loose a Stinging Rain", 1, [Elements.Moon, Elements.Air, Elements.Water]],
        ["Finder", "Traveler's Boon", 0, [Elements.Moon, Elements.Air, Elements.Water]],
        ["Finder", "Offer Passage Between Worlds", 1, [Elements.Sun, Elements.Moon, Elements.Air]],
        ["Finder", "Aid from the Spirit-Speakers", 2, [Elements.Sun, Elements.Fire, Elements.Air, Elements.Animal]],
        ["Finder", "Paths Tied by Nature", 0, [Elements.Sun, Elements.Air, Elements.Earth, Elements.Plant]],
        ["Finder", "Ways of Shore and Heartland", 1, [Elements.Air, Elements.Water, Elements.Earth]],
        ["Finder", "A Circuitous and Wending Journey", 0, [Elements.Moon, Elements.Air]],
)

class Command(BaseCommand):
    help = 'Seed the database'

    def add_arguments(self, parser):
        # parser.add_argument('poll_ids', nargs='+', type=int)
        pass

    @transaction.atomic
    def handle(self, *args, **options):
        for s in spirits:
            Spirit(name=s[0]).save()
        for c in cards:
            elements = ','.join([e.name for e in c[3]])
            if type(c[0]) == type(""):
                Card(name=c[1], type=Card.UNIQUE, spirit=Spirit.objects.get(name=c[0]), cost=c[2], elements=elements).save()
            else:
                Card(name=c[1], type=c[0], cost=c[2], elements=elements).save()

        if settings.DEBUG:
            User.objects.create_superuser(username='admin', password='admin').save()

        self.stdout.write(self.style.SUCCESS('Seeded database'))
