#!/bin/bash

unset GIT_DIR

cd /home/ubuntu/spirit-island
git fetch origin
git reset --hard origin/master

sudo systemctl daemon-reload

echo Restarting services

sudo systemctl restart spirit-island
sudo systemctl restart spirit-island-bot

sleep 5

systemctl status spirit-island
systemctl status spirit-island-bot
