#!/bin/bash

unset GIT_DIR

cd /home/ubuntu/spirit-island
git fetch origin
git reset --hard origin/master

echo Restarting services

systemctl --user restart spirit-island
systemctl --user restart spirit-island-bot

sleep 5

systemctl --user status spirit-island
systemctl --user status spirit-island-bot
