# Generated by Django 4.0.1 on 2022-01-29 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Unique')])),
                ('cost', models.IntegerField()),
                ('elements', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(blank=True, upload_to='screenshot')),
                ('discord_channel', models.CharField(blank=True, default='', max_length=255)),
                ('major_deck', models.ManyToManyField(related_name='major_deck', to='pbf.Card')),
                ('minor_deck', models.ManyToManyField(related_name='minor_deck', to='pbf.Card')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('energy', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('temporary_sun', models.IntegerField(default=0)),
                ('temporary_moon', models.IntegerField(default=0)),
                ('temporary_fire', models.IntegerField(default=0)),
                ('temporary_air', models.IntegerField(default=0)),
                ('temporary_water', models.IntegerField(default=0)),
                ('temporary_earth', models.IntegerField(default=0)),
                ('temporary_plant', models.IntegerField(default=0)),
                ('temporary_animal', models.IntegerField(default=0)),
                ('discard', models.ManyToManyField(blank=True, related_name='discard', to='pbf.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.game')),
                ('hand', models.ManyToManyField(blank=True, related_name='hand', to='pbf.Card')),
                ('play', models.ManyToManyField(blank=True, related_name='play', to='pbf.Card')),
                ('selection', models.ManyToManyField(blank=True, related_name='selection', to='pbf.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('opacity', models.FloatField(default=1.0)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.gameplayer')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='spirit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.spirit'),
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.game')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='spirit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbf.spirit'),
        ),
    ]
