# Generated by Django 4.0.1 on 2022-01-22 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Unique')])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='screenshot')),
                ('major_deck', models.ManyToManyField(related_name='major_deck', to='pbf.Card')),
                ('minor_deck', models.ManyToManyField(related_name='minor_deck', to='pbf.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('energy', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('discard', models.ManyToManyField(related_name='discard', to='pbf.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.game')),
                ('hand', models.ManyToManyField(related_name='hand', to='pbf.Card')),
                ('play', models.ManyToManyField(related_name='play', to='pbf.Card')),
                ('selection', models.ManyToManyField(related_name='selection', to='pbf.Card')),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.spirit')),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.game')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='spirit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pbf.spirit'),
        ),
    ]
