# Generated by Django 4.0.1 on 2022-01-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discord_channel',
            field=models.CharField(default='', max_length=255),
        ),
    ]
