# Generated by Django 4.0.1 on 2022-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Seeding the db was originally done in a separate command, but now that it is a migration, it still needs
        # to be applied as early as possible.
        ('pbf', '0043_seed_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='images',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
