# Generated by Django 4.0.1 on 2022-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0002_gamelog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='aspect',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
