# Generated by Django 4.0.1 on 2022-01-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0002_game_discord_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='screenshot'),
        ),
    ]
