# Generated by Django 4.0.1 on 2022-01-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0003_alter_game_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('opacity', models.FloatField(default=1.0)),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbf.gameplayer')),
            ],
        ),
    ]
