# Generated by Django 4.0.1 on 2022-01-23 19:08

from django.db import migrations
from pbf import models

def create_exploratory_bringer(apps, schema_editor):
    Spirit = apps.get_model("pbf", "Spirit")
    spirit = Spirit(name="Exploratory Bringer")
    spirit.save()
    Card = apps.get_model("pbf", "Card")
    Card(name="Predatory Nightmares", type=models.Card.UNIQUE, spirit=spirit).save()
    Card(name="Dread Apparitions", type=models.Card.UNIQUE, spirit=spirit).save()
    Card(name="Call on Midnight's Dream", type=models.Card.UNIQUE, spirit=spirit).save()
    Card(name="Dreams of the Dahan", type=models.Card.UNIQUE, spirit=spirit).save()

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0003_alter_game_screenshot'),
    ]

    operations = [
        migrations.RunPython(create_exploratory_bringer),
    ]

