# Generated by Django 4.0.1 on 2022-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0003_gameplayer_aspect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='paid_this_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='aspect',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
