# Generated by Django 4.0.1 on 2022-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0004_add_exploratory_bringer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discord_channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
