# Generated by Django 4.0.1 on 2022-02-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0004_alter_card_options_gameplayer_paid_this_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='gained_this_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='energy',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
