# Generated by Django 4.0.1 on 2022-01-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0005_alter_game_discord_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='discard',
            field=models.ManyToManyField(blank=True, related_name='discard', to='pbf.Card'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='hand',
            field=models.ManyToManyField(blank=True, related_name='hand', to='pbf.Card'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='play',
            field=models.ManyToManyField(blank=True, related_name='play', to='pbf.Card'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='selection',
            field=models.ManyToManyField(blank=True, related_name='selection', to='pbf.Card'),
        ),
    ]
