# Generated by Django 4.0.1 on 2022-02-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0006_presence_elements_alter_presence_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='starting_energy',
            field=models.IntegerField(default=0),
        ),
    ]
