# Generated by Django 4.0.1 on 2022-01-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0004_presence'),
        ('pbf', '0006_alter_gameplayer_discard_alter_gameplayer_hand_and_more'),
    ]

    operations = [
    ]
