# Generated by Django 4.0.1 on 2022-03-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0008_alter_gameplayer_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='notes',
        ),
    ]
