# Generated by Django 4.0.1 on 2022-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0009_remove_gameplayer_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ('-id',)},
        ),
    ]
