# Generated by Django 4.0.1 on 2022-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0010_alter_gameplayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discard_pile',
            field=models.ManyToManyField(related_name='discard_pile', to='pbf.Card'),
        ),
    ]
