# Generated by Django 4.0.1 on 2022-03-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0011_game_discard_pile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discard_pile',
            field=models.ManyToManyField(blank=True, related_name='discard_pile', to='pbf.Card'),
        ),
        migrations.AlterField(
            model_name='game',
            name='major_deck',
            field=models.ManyToManyField(blank=True, related_name='major_deck', to='pbf.Card'),
        ),
        migrations.AlterField(
            model_name='game',
            name='minor_deck',
            field=models.ManyToManyField(blank=True, related_name='minor_deck', to='pbf.Card'),
        ),
    ]
