# Generated by Django 4.0.1 on 2022-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0012_alter_game_discard_pile_alter_game_major_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='days', to='pbf.Card'),
        ),
    ]
