# Generated by Django 4.0.1 on 2022-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0013_gameplayer_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discord_channel',
            field=models.CharField(blank=True, choices=[('957389286834057306', '#pbp1-updates'), ('883019769937268816', '#pbp2-updates'), ('703767917854195733', '#bot-testing')], default='', max_length=255),
        ),
    ]
