# Generated by Django 4.0.1 on 2022-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0016_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshot2',
            field=models.ImageField(blank=True, upload_to='screenshot'),
        ),
    ]
