# Generated by Django 4.0.1 on 2022-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0017_game_screenshot2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_air',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_animal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_earth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_fire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_moon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_plant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_sun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='permanent_water',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='discord_channel',
            field=models.CharField(blank=True, choices=[('957389286834057306', '#pbp1-updates'), ('883019769937268816', '#pbp2-updates'), ('1022258668428865586', '#pbp3-updates'), ('1010285070680072192', '#pbp-allspirit-updates'), ('703767917854195733', '#bot-testing')], default='', max_length=255),
        ),
    ]
