# Generated by Django 4.0.1 on 2022-11-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0018_gameplayer_permanent_air_gameplayer_permanent_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discord_channel',
            field=models.CharField(blank=True, choices=[('957389286834057306', '#pbp1-updates'), ('883019769937268816', '#pbp2-updates'), ('1022258668428865586', '#pbp3-updates'), ('1025502499387478127', '#pbp4-updates'), ('1010285070680072192', '#pbp-allspirit-updates'), ('703767917854195733', '#bot-testing')], default='', max_length=255),
        ),
    ]
