# Generated by Django 4.0.1 on 2023-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0019_alter_game_discord_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
