# Generated by Django 4.0.1 on 2023-04-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0020_gameplayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discord_channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
