# Generated by Django 4.0.1 on 2023-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0023_add_nature_incarnate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='impending',
            field=models.ManyToManyField(blank=True, related_name='impending', to='pbf.Card'),
        ),
    ]
