# Generated by Django 4.0.1 on 2023-07-07 14:40

from django.db import migrations

def fix_boon(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")
    card = Card.objects.get(name="Boon of Corrupted Blood")
    card.elements = 'Sun,Fire,Animal'
    card.save()

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0027_gameplayer_healing_alter_card_type'),
    ]

    operations = [
        migrations.RunPython(fix_boon, noop),
    ]
