# Generated by Django 4.0.1 on 2023-07-11 15:45

from django.db import migrations
import sys

def load_ni(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")
    Card(name="Belligerent and Aggressive Crops", cost=1, type=3, elements="Sun,Fire,Plant").save()
    Card(name="Smite the Land with Fulmination", cost=2, type=3, elements="Sun,Fire,Air").save()
    Card(name="Roiling Bog and Snagging Thorn", cost=0, type=0, elements="Moon,Fire,Water,Plant").save()

    # in tests, the database doesn't get seeded,
    # so Growth Through Sacrifice doesn't exist.
    if 'test' not in sys.argv:
        gts = Card.objects.get(name="Growth through Sacrifice")
        gts.type=3
        gts.save()

def delete_ni(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")

    Card.objects.get(name="Belligerent and Aggressive Crops").delete()
    Card.objects.get(name="Smite the Land with Fulmination").delete()
    Card.objects.get(name="Roiling Bog and Snagging Thorn").delete()

    if 'test' not in sys.argv:
        gts = Card.objects.get(name="Growth through Sacrifice")
        gts.type=0
        gts.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0028_auto_20230707_1440'),
    ]

    operations = [
        migrations.RunPython(load_ni, delete_ni),
    ]
