# Generated by Django 4.0.1 on 2023-08-21 16:15

from django.db import migrations

def fix_swalled(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")
    card = Card.objects.get(name="Swalled by the Endless Dark")
    card.name = "Swallowed by the Endless Dark"
    card.save()

def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0029_auto_20230711_1545'),
    ]

    operations = [
        migrations.RunPython(fix_swalled, noop),
    ]
