# Generated by Django 4.0.1 on 2023-09-04 13:51

from django.db import migrations

def load_ni(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")
    card = Card.objects.get(name="Transformative Sacrifice")
    card.elements = 'Moon,Fire,Water,Plant'
    card.save()

def delete_ni(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0030_auto_20230821_1615'),
    ]

    operations = [
        migrations.RunPython(load_ni, delete_ni),
    ]
