# Generated by Django 4.2.11 on 2024-04-03 01:02

from django.db import migrations


def load_ni(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")
    card = Card.objects.get(name="Inspire the Release of Stolen Lands")
    card.elements = 'Sun,Water,Plant,Animal'
    card.save()


def delete_ni(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0031_auto_20230904_1351'),
    ]

    operations = [
        migrations.RunPython(load_ni, delete_ni),
    ]
