# Generated by Django 4.2.11 on 2024-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pbf", "0031_auto_20230904_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayer",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blue", "blue"),
                    ("green", "green"),
                    ("orange", "orange"),
                    ("purple", "purple"),
                    ("red", "red"),
                    ("yellow", "yellow"),
                    ("cyan", "cyan"),
                    ("brown", "brown"),
                    ("pink", "pink"),
                ],
                max_length=255,
            ),
        ),
    ]
