# Generated by Django 4.2.11 on 2024-04-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pbf", "0032_auto_20240403_0102"),
        ("pbf", "0033_alter_gameplayer_color"),
    ]

    operations = []
