from django.db import models, migrations

def set_speeds(apps, schema_editor):
    Card = apps.get_model("pbf", "Card")

    fast_lower = set(name.lower() for name in FAST_CARDS)
    slow_lower = set(name.lower() for name in SLOW_CARDS)

    for card in Card.objects.all():
        if card.name.lower() in fast_lower:
            card.speed = 1
            card.save()
        elif card.name.lower() in slow_lower:
            card.speed = 2
            card.save()
        elif card.name not in ('Roiling Waters', 'Serene Waters', 'Waters Renew', 'Waters Taste of Ruin'):
            raise Exception(f"Don't know what speed to assign to {card.name}")

FAST_CARDS = (
    "A Dreadful Tide of Scurrying Flesh",
    "A Year of Perfect Stillness",
    "Absolute Stasis",
    "Absorb Essence",
    "Aid from the Spirit-Speakers",
    "Bargain of Coursing Paths",
    "Bargains of Power and Protection",
    "Birds Cry Warning",
    "Blazing Intimidation",
    "Blazing Renewal",
    "Blinding Glare",
    "Blood Draws Predators",
    "Bloodwrack Plague",
    "Blur the Arc of Years",
    "Boon of Corrupted Blood",
    "Boon of Swarming Bedevilment",
    "Boon of Vigor",
    "Boon of Watchful Guarding",
    "Call To Guard",
    "Call of the Deeps",
    "Call on Midnight's Dream",
    "Call to Isolation",
    "Call to Trade",
    "Carapaced Land",
    "Concealing Shadows",
    "Confounding Mists",
    "Cycles of Time and Tide",
    "Dark Skies Loose a Stinging Rain",
    "Dark and Tangled Woods",
    "Delusions of Danger",
    "Disorienting Landscape",
    "Domesticated Animals Go Berserk",
    "Draw to the Water's Edge",
    "Dread Apparitions",
    "Dream of the Untouched Land",
    "Dreams of the Dahan",
    "Drift down into Slumber",
    "Elemental Aegis",
    "Elemental Boon",
    "Elemental Teachings",
    "Elusive Ambushes",
    "Encompassing Ward",
    "Enticing Splendor",
    "Entrancing Apparitions",
    "Entrap The Forces Of Corruption",
    "Entwine the Fates of All",
    "Entwined Power",
    "Exaltation of Molten Stone",
    "Exaltation of the Incandescent Sky",
    "Exhale Confusion and Delirium",
    "Favor Of The Sun And Star-Lit Dark",
    "Favors of Steel and Bone",
    "Favors of Story and Season",
    "Fiery Vengeance",
    "Fire in the Sky",
    "Flame's Fury",
    "Flash Floods",
    "Flocking Red-Talons",
    "Flow like Water, Reach like Air",
    "Flowing and Silent Forms Dart By",
    "Gift of Abundance",
    "Gift of Constancy",
    "Gift of Flowing Power",
    "Gift of Furious Might",
    "Gift of Living Energy",
    "Gift of Nature's Connection",
    "Gift of Proliferation",
    "Gift of Searing Heat",
    "Gift of Seismic Energy",
    "Gift of Twinned Days",
    "Gift of Wind-Sped Steps",
    "Gift of the Primordial Deeps",
    "Gift of the Sunlit Air",
    "Grasping Tide",
    "Growth through Sacrifice",
    "Guard the Healing Land",
    "Guardian Serpents",
    "Guide the Way on Feathered Wings",
    "Haunted By Primal Memories",
    "Hazards Spread Across The Island",
    "Indomitable Claim",
    "Infestation of Venomous Spiders",
    "Infinite Vitality",
    "Insatiable Hunger of the Swarm",
    "Instruments of their own Ruin",
    "Intractable Thickets and Thorns",
    "Irresistible Call",
    "Land of Deadfall and Rot",
    "Land of Haunts and Embers",
    "Lightning's Boon",
    "Lure of the Unknown",
    "Mark Territory with Scars and Teeth",
    "Melt Earth into Quicksand",
    "Mesmerized Tranquility",
    "Mysterious Abductions",
    "Nature's Resilience",
    "Offer Passage Between Worlds",
    "Overenthusiastic Arson",
    "Overgrow in a Night",
    "Paralyzing Fright",
    "Peace of the Nighttime Sky",
    "Petition for Smoldering Wrath",
    "Pent-Up Calamity",
    "Plague Ships Sail to Distant Ports",
    "Portents of Disaster",
    "Pour Time Sideways",
    "Powerstorm",
    "Prey on the Builders",
    "Promises of Protection",
    "Pursue with Scratches, Pecks, and Stings",
    "Pyroclastic Bombardment",
    "Pyroclastic Flow",
    "Quicken the Earth's Struggles",
    "Radiant and Hallowed Grove",
    "Razor-Sharp Undergrowth",
    "Reach from the Infinite Darkness",
    "Reaching Grasp",
    "Resounding Footfalls Sow Dismay",
    "Rites of the Land's Rejection",
    "Roiling Bog and Snagging Thorn",
    "Rumblings Portend a Greater Quake",
    "Sacrosanct Wilderness",
    "Sap the Strength of Multitudes",
    "Scream Disease Into The Wind",
    "Set Them On An Ever-Twisting Trail",
    "Settle Into Hunting-Grounds",
    "Share Secrets of Survival",
    "Skies Herald The Season Of Return",
    "Sky Stretches to Shore",
    "Sleep and Never Waken",
    "Solidify Echoes of Majesty Past",
    "Spill Bitterness into the Earth",
    "Spur on with Words of Fire",
    "Steam Vents",
    "Strike Low with Sudden Fevers",
    "Strong And Constant Currents",
    "Stubborn Solidity",
    "Study the Invaders' Fears",
    "Sucking Ooze",
    "Sudden Ambush",
    "Surrounded by the Dahan",
    "Swallowed by the Endless Dark",
    "Swallowed by the Wilderness",
    "Swarming Wasps",
    "Sweltering Exhaustion",
    "Talons of Lightning",
    "Tempest of Leaves and Branches",
    "Terrifying Nightmares",
    "Terrifying Rampage",
    "The Past Returns Again",
    "The Trees and Stones Speak of War",
    "Thickets Erupt with Every Touch of Breeze",
    "Threatening Flames",
    "Tigers Hunting",
    "Transformative Sacrifice",
    "Traveler's Boon",
    "Treacherous Waterways",
    "Trees Radiate Celestial Brilliance",
    "Unbearable Deluge",
    "Unearth a Beast of Wrathful Stone",
    "Unleash a Torrent of the Self's Own Essence",
    "Unlock the Gates of Deepest Power",
    "Unnerving Pall",
    "Veil the Night's Hunt",
    "Vengeance of the Dead",
    "Vigor of the Breaking Dawn",
    "Visions of Fiery Doom",
    "Voice of Command",
    "Walls of Rock and Thorn",
    "Weave Together the Fabric of Place",
    "Winds of Rust and Atrophy",
    "Words of Warning",
    "Worms and Bugs Enrich the Soil",
    "Wrap in Wings of Sunlight",
)

SLOW_CARDS = (
    "A Circuitous and Wending Journey",
    "Absorb Corruption",
    "Accelerated Rot",
    "Angry Bears",
    "Animated Wrackroot",
    "Asphyxiating Smoke",
    "Bats Scout For Raids By Darkness",
    "Belligerent and Aggressive Crops",
    "Blood Water and Bloodlust",
    "Blooming of the Rocks and Trees",
    "Bombard with Boulders and Stinging Seeds",
    "Boon of Ancient Memories",
    "Boon of Growing Power",
    "Boon of Reimagining",
    "Boon of Resilient Power",
    "Call of the Dahan Ways",
    "Call on Herders for Aid",
    "Call to Bloodshed",
    "Call to Ferocity",
    "Call to Migrate",
    "Call to Tend",
    "Call to Vigilance",
    "Cast down into the Briny Deep",
    "Cleansing Floods",
    "Coordinated Raid",
    "Crops Wither and Fade",
    "Death Falls Gently from Open Blossoms",
    "Desiccating Winds",
    "Devouring Ants",
    "Dire Metamorphosis",
    "Dissolve the Bonds of Kinship",
    "Dissolving Vapors",
    "Draw Towards a Consuming Void",
    "Draw of the Fruitful Earth",
    "Drought",
    "Dry Wood Explodes In Smoldering Splinters",
    "Eerie Noises and Moving Trees",
    "Emerge from the Dread Night Wind",
    "Ever-Multiplying Swarm",
    "Exaltation of Echoed Steps",
    "Exaltation of Grasping Roots",
    "Exaltation of Tangled Growth",
    "Exaltation of the Re-Forming Land",
    "Favors Called Due",
    "Ferocious Rampage",
    "Fetid Breath Spreads Infection",
    "Fields Choked with Growth",
    "Fire and Flood",
    "Flash-Fires",
    "Fleshrot Fever",
    "Flow Downriver, Blow Downwind",
    "Focus the Land's Anguish",
    "Focus the Sun's Rays",
    "Forests of Living Obsidian",
    "Foul Vapors and Fetid Muck",
    "Foundations Sink into Mud",
    "Fragments of Yesteryear",
    "Frightful Keening",
    "Gather the Scattered Light of Stars",
    "Gift of Power",
    "Gift of the Untamed Wild",
    "Gnawing Rootbiters",
    "Gold's Allure",
    "Grant Hatred a Ravenous Form",
    "Harbingers of the Lightning",
    "Herd Towards the Lurking Maw",
    "Here there be Monsters",
    "Impersonate Authority",
    "Incite the Mob",
    "Infested Aquifers",
    "Infesting Spores",
    "Inflame the Fires of Life",
    "Inspire a Winding Dance",
    "Inspire the Release of Stolen Lands",
    "Jagged Shards Push from the Earth",
    "Lava Flows",
    "Like Calls to Like",
    "Manifest Incarnation",
    "Manifestation of Power and Glory",
    "Mantle of Dread",
    "Melt Earth to Slag",
    "Mists of Oblivion",
    "Open Shifting Waterways",
    "Pact of the Joined Hunt",
    "Paths Tied by Nature",
    "Perils of the Deepest Island",
    "Pillar of Living Flame",
    "Plaguebearers",
    "Plows Shatter on Rocky Ground",
    "Poisoned Dew",
    "Poisoned Land",
    "Predatory Nightmares",
    "Prowling Panthers",
    "Pull Beneath the Hungry Earth",
    "Purifying Flame",
    "Radiating Tremors",
    "Raging Storm",
    "Rain of Ash",
    "Rain of Blood",
    "Ravaged Undergrowth Slithers Back to Life",
    "Regrow from Roots",
    "Renewing Boon",
    "Renewing Rain",
    "Rituals of Destruction",
    "River's Bounty",
    "Rouse the Trees and Stones",
    "Rumbling Earthquakes",
    "Savage Mawbeasts",
    "Savage Transformation",
    "Scarred and Stony Land",
    "Scatter to the Winds",
    "Scour the Land",
    "Sea Monsters",
    "Sear Anger Into The Wild Lands",
    "Shadows of the Burning Forest",
    "Shape the Self Anew",
    "Shatter Homesteads",
    "Smite the Land with Fulmination",
    "Smothering Infestation",
    "Softly Beckon Ever Inward",
    "Song of Sanctity",
    "Stem the Flow of Fresh Water",
    "Stinging Sandstorm",
    "Storm-Swath",
    "Strangling Firevine",
    "Sunset's Fire Flows Across The Land",
    "Surging Lahar",
    "Swallow the Land-Dwellers",
    "Sweep into the Sea",
    "Teeming Rivers",
    "Teeth Gleam from Darkness",
    "Terrifying Chase",
    "Territorial Strife",
    "Terror Turns To Madness",
    "Terror of the Hunted",
    "The Fog Closes In",
    "The Jungle Hungers",
    "The Land Thrashes in Furious Pain",
    "The Shore Seethes With Hatred",
    "The Wounded Wild Turns on its Assailants",
    "Thriving Chokefungus",
    "Tidal Boon",
    "Too Near the Jungle",
    "Tormenting Rotflies",
    "Towering Wrath",
    "Transform to a Murderous Darkness",
    "Tsunami",
    "Turmoil's Touch",
    "Twilight Fog brings Madness",
    "Twist Perceptions",
    "Twisted Flowers Murmur Ultimatums",
    "Unbearable Gaze",
    "Uncanny Melting",
    "Unexpected Tigers",
    "Unnerving Attention",
    "Unquenchable Flames",
    "Unrelenting Growth",
    "Utter a Curse of Dread and Bone",
    "Vanish Softly Away, Forgotten by All",
    "Voice of Thunder",
    "Volcanic Eruption",
    "Voracious Growth",
    "Wash Away",
    "Ways of Shore and Heartland",
    "Weep For What Is Lost",
    "Whispered Guidance Through the Night",
    "Wither Bodies, Scar Stones",
    "Wrack with Pain and Grief",
)

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0040_game_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='speed',
            # a temporary default of 0
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Fast'), (2, 'Slow')], default=0),
        ),
        # reverse doesn't need to do anything; the field will be deleted.
        migrations.RunPython(set_speeds, migrations.RunPython.noop),
        # remove the default
        migrations.AlterField(
            model_name='card',
            name='speed',
            # remove the temporary default
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Fast'), (2, 'Slow')]),
        ),
    ]
