# Generated by Django 4.2.16 on 2025-06-19 04:25

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0047_impending_this_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='spirit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pbf.spirit'),
        ),
    ]
