# Generated by Django 4.2.16 on 2025-06-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0048_card_spirit_blank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='starting_energy',
            new_name='base_energy_per_turn',
        ),
    ]
