# Generated by Django 4.2.16 on 2025-06-19 21:11

from django.db import migrations, models
from django.db.models import F

def init_last_ready(apps, schema_editor):
    GamePlayer = apps.get_model('pbf', 'GamePlayer')
    # Decided not to set this.
    # It may be inaccurate if the player has already done some operations since turn start.
    # GamePlayer.objects.filter(ready=False).update(last_unready_energy=F('energy'))
    GamePlayer.objects.filter(ready=True).update(last_ready_energy=F('energy'))

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0049_rename_starting_energy_gameplayer_base_energy_per_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='last_ready_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='last_unready_energy',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(init_last_ready, reverse_code=migrations.RunPython.noop),
    ]
