# Generated by Django 4.2.16 on 2025-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0050_gameplayer_last_ready_energy_and_last_unready_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='always_suffix_screenshot',
            field=models.BooleanField(default=False),
        ),
    ]
