# Generated by Django 4.2.16 on 2025-06-22 22:48

from django.db import migrations, models
import pbf.models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0051_game_always_suffix_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to=pbf.models.Game.screenshot_with_suffix),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshot2',
            field=models.ImageField(blank=True, upload_to=pbf.models.Game.screenshot_with_suffix),
        ),
    ]
