# Generated by Django 5.2.4 on 2025-07-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0053_exploratory_bringer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='spoiler_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
