# Generated by Django 5.2.4 on 2025-07-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0054_gamelog_spoiler_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='bargain_cost_per_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='bargain_paid_this_turn',
            field=models.IntegerField(default=0),
        ),
    ]
