# Generated by Django 5.2.5 on 2025-09-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0057_rename_shifting_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='exclude_from_deck',
            field=models.BooleanField(default=False),
        ),
    ]
