# Generated by Django 5.2.6 on 2025-09-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0059_vengeance_of_the_dead_exploratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='base_energy_per_turn',
        ),
    ]
