# Generated by Django 5.2.10 on 2026-01-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0061_covets_gleaming_shards_of_earth_v14'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='scenario',
            field=models.ManyToManyField(blank=True, related_name='scenario', to='pbf.card'),
        ),
    ]
