# Generated by Django 5.2.10 on 2026-01-07 08:22

from django.db import migrations, models

SPECIAL_TO_UNIQUE = (
    'Belligerent and Aggressive Crops',
    'Smite the Land with Fulmination',
)
UNIQUE_TO_RETIRED = (
    'Favors of Steel and Bone v1.2.1',
    'Favors of Steel and Bone v1.3',
    'Melt Earth to Slag v1.2.1',
    'Melt Earth to Slag v1.3',
    'Petition for Smoldering Wrath v1.2.1',
)

def change_types(apps, changes):
    Card = apps.get_model('pbf', 'Card')
    for (names, old, _) in changes:
        found_names = Card.objects.filter(name__in=names, type=old).values_list('name', flat=True)
        if list(found_names) != list(names):
            raise ValueError(f"looked for {names} and found {found_names}")
    for (names, old, new) in changes:
        Card.objects.filter(name__in=names, type=old).update(type=new)

def fwd(apps, schema_editor):
    change_types(apps, ((SPECIAL_TO_UNIQUE, 3, 2), (UNIQUE_TO_RETIRED, 2, 3)))

def rev(apps, schema_editor):
    change_types(apps, ((SPECIAL_TO_UNIQUE, 2, 3), (UNIQUE_TO_RETIRED, 3, 2)))

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0062_gameplayer_scenario'),
    ]

    operations = [
        migrations.RunPython(fwd, rev),
    ]
