# Generated by Django 5.2.10 on 2026-01-07 09:14

from django.db import migrations, models

HEALING = ('Roiling Waters', 'Serene Waters', 'Waters Renew', 'Waters Taste of Ruin')

def change_types(apps, changes):
    Card = apps.get_model('pbf', 'Card')
    for (names, old, _) in changes:
        found_names = Card.objects.filter(name__in=names, type=old).values_list('name', flat=True)
        if list(found_names) != list(names):
            raise ValueError(f"looked for {names} and found {found_names}")
    for (names, old, new) in changes:
        Card.objects.filter(name__in=names, type=old).update(type=new)

def fwd(apps, schema_editor):
    change_types(apps, ((HEALING, 3, 4),))

def rev(apps, schema_editor):
    change_types(apps, ((HEALING, 4, 3),))

class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0063_reclassify_uniques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Unique'), (3, 'Special'), (4, 'Healing')]),
        ),
        migrations.RunPython(fwd, rev),
    ]
