# Generated by Django 5.2.10 on 2026-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbf', '0064_card_type_add_healing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.IntegerField(choices=[(0, 'Minor'), (1, 'Major'), (2, 'Unique'), (3, 'Retired'), (4, 'Healing')]),
        ),
    ]
