name: lint
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Weekly.
    - cron: "0 0 * * 0"

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.12'
          # unlikely to see any changes in linting between oldest and newest,
          # so just those two will suffice
          - '3.14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install ruff
      # E701: multiple statements on one line
      - run: ruff check --ignore E701
